### ISSUE TITLE
Installation error - can't find Microsoft SDKS/.../lib

### ISSUE THREAD

**Issue by stavlocker** [redis/hiredis-py#74]
Hi. I'm trying to install `hiredis-py` but I'm getting this issue:

    error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1\\lib'
In the specified folder (`v8.1`) I only have a folder called `ExtensionSDKs`. I couldn't find a reference for needing a Microsoft SDK anywhere here. Am I doing something wrong?

Thanks in advance.

**Comment by michael-grunder** [comment]
Hi,

I don't have any Windows machine to test on, but these links appear related:
https://stackoverflow.com/questions/50400571/filenotfounderror-microsoft-sdks-windows-v8-1-lib
https://stackoverflow.com/questions/51476784/how-to-install-visual-studio-2015-platformsdk-now

**Comment by ifduyue** [comment]
Hello,

What's your environment like? Python version? Installed Visual Studio or Build Tools for Visual Studio？
Did you select Windows 8.1 SDK when installing Build Tools for Visual Studio? Windows 8.1 SDK is not selected by default.

This link [1] might be helpful

[1] https://stackoverflow.com/questions/43704734/how-to-fix-the-error-windows-sdk-version-8-1-was-not-found

**Comment by ifduyue** [comment]
@stavlocker Hello. 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/568900/46744639-1f9d2b00-ccde-11e8-9292-1a269a85e7a1.png">
This is my  vistual studio installation details and pip install hiredis works fine.

Since hiredis-py is a Python C extension, we need C compiler/linker as we install it.
However, if binary wheels are provided, we can install hiredis-py directly without C toolchain. I'm working on this, but I'm a little busy these days. You can try conda for now, conda-forge has built binary wheels for hiredis https://anaconda.org/conda-forge/hiredis https://conda.io/docs/

**Comment by temka1234** [comment]
If you want to install hiredis without conda you can download archive for your win version
https://anaconda.org/conda-forge/hiredis/files
and unpack content of "Lib/site-packages/" to your python "site-packages".

**Comment by ifduyue** [comment]
@stavlocker wheels for windows are available in v0.3.0, could you try it and see if it solves the problem?
